apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-k8s-2
  name: hello-k8s-2
spec:
  containers:
  - image: nginx:1.11
    name: hello-k8s-2
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred 
